module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'apps/**/*.(t|j)s',
    'libs/**/*.(t|j)s',
    '!apps/**/*.spec.ts',
    '!libs/**/*.spec.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/*.d.ts',
    '!**/main.ts',
  ],
  coverageDirectory: './coverage',
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/coverage/',
  ],
  moduleNameMapping: {
    '^@mcom/common(|/.*)$': '<rootDir>/libs/common/src/$1',
    '^@mcom/database(|/.*)$': '<rootDir>/libs/database/src/$1',
    '^@mcom/messaging(|/.*)$': '<rootDir>/libs/messaging/src/$1',
    '^@mcom/types(|/.*)$': '<rootDir>/libs/types/src/$1',
    '^@mcom/auth(|/.*)$': '<rootDir>/libs/auth/src/$1',
    '^@mcom/cache(|/.*)$': '<rootDir>/libs/cache/src/$1',
    '^@mcom/validation(|/.*)$': '<rootDir>/libs/validation/src/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  globalSetup: '<rootDir>/tests/global-setup.ts',
  globalTeardown: '<rootDir>/tests/global-teardown.ts',
  testTimeout: 30000,
  maxWorkers: '50%',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
};